import {el} from './dom.js';
import {SCALE_LABS} from './scale-labs.js';
const families=["Roads and streets", "Fleet size and supply", "Demand, crowds and weather", "Reading a run and a result", "Depot work and capacity", "Energy and charging", "Launching a new area", "Recall, release and depot choice", "Scaling the fleet"];
const models=["Fleet day", "Street lab", "Four-area experiments", "Scale lab"];
const evidence=["replay", "one-seed", "paired"];
const make=(id,a)=>Object.freeze({id,family:families[a[0]],model:models[a[1]],evidence:evidence[a[2]],what_why:a[3],how:a[4],look_for:a[5],ops_takeaway:a[6],limits:"Each model has its own assumptions, so numbers from different models are not interchangeable.",kind:a[7]??null});
export const LESSON_FRAMES=Object.freeze(Object.fromEntries([...Object.entries({
"bay-area":[0,0,0,"How far riders are from free cars sets how far cars drive empty. Before choosing a service zone, an operator needs to know how much car time goes to pickups.","Same fleet and demand rate; only the served places change. Trips follow frozen OSM major roads between 18 anchors, with no turn rules, one-way streets or local access. Run all 18, then SF and SFO only.","Read completed trips, empty pickup distance and charging queues as the served places change.","An ops team would check pickup distance and depot charging together in its own service area."],
"vehicle-mix":[1,0,1,"Does a vehicle type change fleet output, and through which assumption? Planners compare energy use, depot work time and charge limits, not names.","Press Compare I-PACE, mixed, Ojai: the same requests replay with 0, 50 and 100% Ojai. Profiles differ in battery size, energy per km, charge limit, and cleaning and upload time. Ojai values are invented.","Compare completed trips, energy use and depot time across vehicle profiles.","An ops team would check which charging cap binds in its own operation before choosing a vehicle profile."],
"fleet-day":[1,0,1,"Is this fleet short of cars or of depot capacity? Buying the wrong one leaves riders unserved and ties up scarce sites.","Run the day, then press Compare fleet & depot sizes: the same requests replay with 12, 24, 36 and 48 cars, then 1 to 6 depots. Only that count changes. Demand and sites are synthetic.","Compare how completed trips respond to cars and to depots, and note whether any tested depot count reaches the completion target.","An ops team would check how much car time goes to empty pickup driving before sizing a fleet or adding a site."],
"weather-day":[2,0,0,"Rain slows trips, raises energy use and adds riders at once. An ops team needs to know which of these removes the most completed service.","Rain multiplies travel time by 1.3, energy by 1.12 and demand by 1.12; heat uses 1.05, 1.25 and 1.05. Demand changes too, so compare counts. Declared multipliers only: no grip, visibility or sensor model.","Read completed and unserved counts alongside travel time and energy; weather changes demand too.","An ops team would test weather travel assumptions against its own trip records."],
"rush-hour":[2,0,0,"Can a fleet sized for average demand absorb a peak, and does the shortage clear afterward? Charging and depot plans depend on the answer.","This lesson starts at 16:00 and raises base demand from 30 to 45 per hour. Peaks run 07-10 and 16-19 at 1.6x demand and 1.25x travel. Both 8 hour windows contain 3 peak hours, so start time alone changes nothing.","Read unserved requests by hour alongside completed trips across the whole window.","An ops team would measure peak and all day service gaps separately in its own records."],
"full-cycle":[3,0,0,"Fleet totals hide single car days. Following one car shows where its minutes go: empty driving, rider trips, depot queues and depot work.","Cars visit a depot after 2 trips instead of 3. Choose a car, then use Next activity or a stage button to step through pickup, trip, depot drive, cleaning, charging and upload.","Follow a car through pickup, trip, depot drive and each depot step, then read completed trips and stored energy.","An ops team would compare depot cadence and end of window energy in its own operation."],
"depot-count":[4,0,1,"Is a service shortfall about too few depots or too few cars? Each depot adds bays, ports and power, so its value depends on which one limits service.","The same demand runs with 1 to 6 depots (fleet fixed) and 12 to 48 cars (one depot). Every added depot brings its own bays, ports and site power. Target: 95% of all requests done by the end of the run.","Read the completion target alongside the fleet and depot comparisons; each site bundles several resources.","An ops team would test car supply and individual site resources separately in its own operation."],
"cleaning":[4,0,0,"Cars wait for a cleaning bay between trips. Do fewer bays and more frequent visits keep cars from riders long enough to change service?","Fleet day with 1 cleaning bay per depot and a depot visit every 2 trips: two changes at once. Demand, fleet and places stay the same. Clean time is fixed and staff are unlimited. One replay.","Read completed and unserved requests before the average wait, which counts completed trips only. Then compare queue minutes at each depot stage.","An ops team would test cleaning cadence and bay count as separate changes."],
"charging":[5,0,0,"Can a fleet that starts the day low on battery recharge in time for the next rider? Charging is the longest depot step, so it sets how fast cars come back.","Cars start at 40% instead of 65%. Charging is linear: each car gets the lowest of port kW, its own limit and site kW split across active ports. No taper, heat or battery wear.","Read delivered power per car and charging queues alongside completed trips.","An ops team would check site power per occupied port in its own depot records."],
"shared-power":[5,0,0,"If a depot's power supply is capped, do extra charge ports help? Port count is easy to see; the site kW limit is what sets how fast cars refill.","4 ports rated 80 kW share 40 kW per depot, split equally among charging cars. Compare 2, 4 or 8 ports at 40 kW, then raise site power with 4 ports. Demand and fleet stay fixed.","Compare delivered energy and finished depot visits with port count and site power.","An ops team would compare port ratings with delivered power in its own operation."],
"software":[4,0,0,"How much rider time does a software update policy take? Update length and how often cars get one both add depot minutes before a car is ready.","Updates run first on scheduled visits, at a fixed time, in limited stations per depot. This lesson sets 30 min on every visit (default: 12 min, every 2nd visit). No failed or rolled-back updates.","Read software queue time, then charging queue time and completed trips.","An ops team would measure update minutes per car and the next depot step in its own records."],
"upload":[4,0,0,"Can moving trip data off a car keep it from riders? Upload is the last depot step, so a slow transfer holds a car that is already clean and charged.","Upload takes a fixed time in limited stations per depot, after charging. This lesson sets 30 min and 1 station (default: 6 min, 2 stations). No bytes, bandwidth sharing or retries.","Read upload waiting and active time, then the charging queue and completed trips.","An ops team would test transfer duration separately from station count in its own operation."],
"staffing-readiness":[4,0,1,"Cars wait for cleaning. Does the depot need another cleaning worker or another bay? Adding the wrong one leaves riders waiting just the same.","One seed, same demand: 16 cars, 1 depot, 18 min base cleaning after every trip. Baseline has 1 worker and 3 bays; one arm adds a worker, the other adds a bay. Descriptive only.","Read the blocker minutes first: what each queued clean was waiting for. Then compare completed trips in the three runs.","An ops team would log what each waiting car lacks, a worker or a bay, before adding either."],
"power-redistribution":[5,0,2,"Some cars accept less power than their share. Can the depot pass that unused power to other cars and get them back to riders sooner?","12 paired seeds, 4 hours, 24 cars, 8 ports sharing 120 kW; I-PACE accepts 10 kW. Equal shares versus redistributing unused power. All else the same; linear charging, no taper.","Read completion against its margin, then charging minutes and unfinished energy per seed; a rule can move energy without freeing cars in time.","An ops team would check that a charging rule frees a car before its next peak."],
"deadline-charging":[5,0,2,"When power is short, does charging the cars needed soonest first help? Reordering can speed some cars and delay others.","Same 24 cars, 8 ports, 120 kW. Redistribution vs deadline-first charging; jobs waiting 60 min or more go oldest first. Deadlines are tiers by car (45, 90 or 135 min after the visit starts).","Read completed trips, ready and missed deadlines, then unfinished depot visits.","An ops team would check who waits under a priority rule in its own depot records."],
"resource-freshness":[5,0,2,"Charger status reports arrive late. Does it help to stop counting a charger once its last report is too old? Stale counts make the planner try failed ports.","4 of 8 ports fail from minute 10 to 100. Status arrives 8 min late and stays valid 10 min. Last-known vs fresh-only status. A rejected try moves to the next port in the same minute.","Read rejected tries and status error beside completed service and outage timing.","An ops team would compare its status delay with its declared validity window."],
"airport-preparation":[2,0,2,"A synthetic arrival wave reaches SFO. Does staging cars before riders ask help? Airport pickups may improve while other areas and depot work pay for it.","Same passenger wave and 24 cars in both arms. Reactive dispatch vs staging up to 6 cars from a declared wave estimate; the policy never sees actual requests. Fictional access rule.","Read airport pickups within target beside non airport service, unfinished work and stored energy.","An ops team would size staging against an energy reserve in its own operation."],
"region-launch":[6,0,1,"If new charging ports come online 90 minutes late, how much rider service is lost? Launch teams need to know which commissioning dates carry service risk.","Two runs on Region B with the same demand seed: ports commissioned at minute 0 versus minute 90. All else the same. Sites, tasks and owners are fictional; setup checks are not inspections.","Read completed trips and late or missed pickups first; on time pickups made before the delay window cannot show it.","An ops team would give each port commissioning task an owner and a date, then rehearse a slip against its own peak."],
"street-first":[0,1,1,"Bridge rush: when 1st Street backs up toward the Bay Bridge, how many rider journeys still finish, and are East Bay trips the only ones hit?","Defaults: 24 AVs, 36 rider requests an hour, 900 other vehicles an hour, most on 1st Street, and a 75% capacity loss from minute 15 to 90. Compare route policies runs both rules on one demand.","Read finished and expired journeys with empty distance and nearby queues; a detour can trade one measure against another.","An ops team would test a routing rule on bridge-bound legs in its own trip records, guarding empty distance."],
"street-harrison":[0,1,1,"SoMa ramp feeders: if AVs detour around a jammed Harrison and Bryant approach, does service improve, or does the queue just move to the next street?","Defaults with the incident and about 60% of other traffic on Harrison, Bryant, Essex and 4th. Queue-aware routes weigh current queues, full blocks and the incident when each leg starts.","Read finished journeys, empty distance and neighbouring street queues together.","An ops team would test incident severity triggers against its own corridor records."],
"street-stockton":[0,1,1,"Chinatown friction: when crossings, buses and deliveries slow how fast Stockton Street discharges, how much fleet service is lost near the pickup?","Friction is a capacity loss on Stockton and its tunnel from minute 15 to 90; pedestrians and buses are not modeled one by one. Try 0, 50 and 95% loss, then pickup dwell, then compare routes.","Read finished journeys alongside pickup exit queues and empty distance.","An ops team would test pickup exits against its own street and rider records."],
"street-van-ness":[0,1,1,"Van Ness signals: if a signal corridor slows trips, can a larger fleet make up the lost service, or does the street still set the pace?","Van Ness with the shared synthetic 90 second signal cycle and imported OSM turn restrictions; no signal control or BRT lane. Run 12, 24, 36 and 48 AVs on the same seed and compare.","Compare pickup wait and expiries with ride time at each fleet size, and compare ride time with a run that has no other traffic.","An ops team would compare ride time with a no traffic baseline before blaming a corridor."],
"street-embarcadero":[0,1,1,"Waterfront event: when event traffic fills The Embarcadero near the pickup point, what happens to rider service, including trips to SFO?","Event pressure is the Other road traffic setting: about 60% of it runs along The Embarcadero, and about half of pickups start at the Ferry Building approach. Try 0, 450 and 900 vehicles/h.","Read finished, expired and unfinished journeys before the boarded rider pickup average.","An ops team would test pickup locations away from an event street in its own operation."],
"street-lombard":[0,1,1,"Lombard visitor queue: does a slow, famous block tie up the fleet, or do vehicles lose time on the streets around it?","Defaults with the incident and about 60% of other traffic on Lombard. Use Largest queue, then Inspect a block, to see which street holds the most queued vehicles.","Inspect nearby streets at the busiest moment alongside finished journeys.","An ops team would check pickup exits and neighbouring queues in its own corridor records."],
"bay_teaching_map":[3,2,0,"Before changing anything: where does a normal fleet day lose time? A baseline shows which area waits longest and which depot queues.","120 cars in four zones, four depots, peaks from 07:00 and 16:00, a depot visit every 10 trips, recall at D2 00:30, release at 05:45. Travel variation is 0, so every replay repeats.","Read rider wait by area and hour next to depot bay queues.","An ops team would map its own waits and depot queues by hour before choosing a change.","decision"],
"L1":[2,2,2,"Same fleet, same declared daily total: does it matter when riders ask? Fleets are sized for peaks, and a daily average can hide an evening shortfall.","Flat versus peaked demand with the same declared total. Primary: rider wait p90 from 16:00 to 19:00, 60 s margin. Guardrail: unserved share. 20 paired seeds.","Read evening wait and unserved share together on the same declared demand total.","An ops team would size and schedule its fleet against peak windows in its own records.","condition"],
"L2a":[4,2,2,"San Jose runs with 12 cars. Does cutting SJ-1 from 3 cleaning bays to 1 make its riders wait longer? Find what binds before cutting capacity.","12 San Jose cars, a depot visit every 5 trips. One change: SJ-1 bays 3 to 1. Primary: San Jose wait p90, 16:00 to 19:00, 60 s margin. 20 paired seeds.","Read San Jose evening wait beside SJ-1 bay wait and the declared margin.","An ops team would check which resource binds and write a queue guardrail before a bay test.","decision"],
"L2b":[4,2,2,"The L2a bay cut with one extra rule written first: SJ-1 bay wait may not grow by more than 10 minutes. Does a rule declared in advance change the call?","Identical arms and seeds to L2a: SJ-1 cleaning bays 3 to 1, with 12 San Jose cars. Added guardrail: SJ-1 bay wait p90, max harm 600 s, declared before the run.","Compare this card's recommendation with L2a's: the runs are the same, only the declared guardrails differ.","An ops team would write a guardrail for the resource it cuts before running any capacity test.","decision"],
"L3":[7,2,2,"When a depot visit comes due, does a car do better at its home depot or the nearest one? The rule moves load between depots and shapes next-morning supply.","Evening highway slowdown set. One change: home depot to nearest depot. Primary: San Francisco wait p90, D2 07:00 to 09:00. Guardrails: congested empty driving, SJ-1 lot, unserved.","Read morning rider wait beside each depot's queues and lot use; each case has one rider draw.","An ops team would write a guardrail for every depot a routing rule can load in its own operation.","decision"],
"UC-01":[3,2,2,"Does the test say no change when nothing changes? A null check shows the harness is not inventing differences.","Both arms set trips between depot visits to 10. Same riders and travel draws in both arms. Primary: rider wait p90, 30 s margin. 20 paired seeds.","Read the paired gap and interval when both arms have the same setting.","An ops team would test an identical arm control in its own tooling before a changed arm.","decision"],
"UC-02":[1,2,2,"San Jose starts with 16 cars, half the map's 32. Do 8 more cut its morning wait, and do neighbours gain too? A first fleet sizing question for one area.","One change: San Jose cars 16 to 24; other areas stay the same. Primary: San Jose wait p90, 07:00 to 09:00, 60 s margin. Guardrails: unserved share, all areas and San Francisco.","Read San Jose morning wait and both unserved guardrails.","An ops team would test a fleet size ladder against its own morning demand.","decision"],
"UC-03":[3,2,2,"Can a wait metric improve because riders gave up? Watching only wait percentiles can reward lost riders.","One change: rider patience 20 to 5 minutes. Primary: rider wait p90, 30 s margin. Guardrail: unserved share, max harm 1 point. 20 paired seeds.","Read rider wait with unserved share and the counted population.","An ops team would check who is absent from each wait metric in its own records.","decision"],
"UC-05":[0,2,2,"How much of San Jose's evening wait comes from slow highways? This compares free-flowing highways with a x1.6 slowdown: a condition, not a decision.","One change: every highway from free flow (x1.0) to x1.6, 16:00 to 19:00; the map's own evening sits between. Primary: San Jose wait p90, 17:00 to 20:00, 60 s margin. Guardrails: unserved, available fleet.","Read highway exposure beside rider wait, unserved share and available fleet.","An ops team would map which areas depend on highway trips in its own operation.","condition"],
"UC-08a":[4,2,2,"Would two more cleaning bays at SF-1 shorten rider waits, or is the bay not what keeps cars from riders?","Four-area experiments: SF-1 with 4 or 6 cleaning bays, same riders, 20 paired seeds that vary travel times only. Rider wait p90 is the main result, 30 s margin; unserved share is the guardrail.","Read rider wait p90 against its margin. A depot change can relieve its own queue while rider wait stays inside the margin.","An ops team would check whether cars queued at a depot are the ones riders need at the peak before adding bays there.","decision"],
"UC-08b":[4,2,2,"Would a 15 minute clean instead of 20 return cars to riders sooner? A faster process is an alternative to more bays.","One change: clean time 20 to 15 minutes at every depot. Primary: rider wait p90 over the whole run, 30 s margin. Guardrail: unserved share. 20 paired seeds.","Read the rider wait interval and depot turnaround together.","An ops team would write the practical margin before testing process time in its own operation.","decision"],
"UC-10":[4,2,2,"Same 11 cleaning bays: pool 6 at SF-1 with 1 at SJ-1, or spread them 4 and 3? A layout choice that adds no capacity.","Rule: nearest depot with a free stall. One change: bays 6, 2, 1, 2 to 4, 2, 3, 2 at SF-1, SF-2, SJ-1, EB-1. Primary: rider wait p90, 30 s margin. Three guardrails.","Read rider wait beside depot bay queues and depot choice.","An ops team would check where its routing rule sends cars before distributing bays.","decision"],
"OPS-01":[1,2,2,"Evening peak in San Francisco: few free cars, long waits. Would 12 more cars help riders, and what do they add to the overnight depot wave?","Only the SF fleet changes, 40 to 52 cars all run. Same riders and roads, 20 paired seeds. Extra cars sleep at SF-1 and SF-2. Staff and charging are not modeled.","Read the evening wait against its margin, then each guardrail: extra cars also join the overnight depot queue.","An ops team would size the overnight depot wave before staging peak cars, and set the allowed overnight bay wait first.","decision"],
"OPS-02":[7,2,2,"Riders still request after midnight. Would recalling cars at 02:00 instead of 00:30 serve them faster, and does the later depot wave spill into the morning?","Only the recall time moves, 00:30 to 02:00 on day 2; the 05:45 release stays. Same riders and 20 paired seeds. No closing time surge, night crew hours or charging windows.","Read late night rider wait beside depot queues and morning availability.","An ops team would test a morning readiness guardrail in its own recall experiments.","decision"],
"OPS-03":[7,2,2,"Depot visits every 10 trips take SF cars off the street in the evening peak. Would visiting every 15 trips serve more riders, and what happens at the depots?","Only the cleaning cadence changes, 10 to 15 trips, for every car at every hour; the model cannot defer only in the peak. Same riders and 20 paired seeds. Cabin condition is not modeled.","Read evening unserved share and depot waits by window.","An ops team would measure cabin condition and depot waits alongside visit cadence in its own records.","decision"],
"OPS-04":[7,2,2,"Peninsula cars sleep at SF depots and go home at 05:45. Would releasing them at 05:00 put San Francisco in better shape for the morning peak?","Only the release time moves, 05:45 to 05:00 on day 2; the recall stays at 00:30. Same riders and 20 paired seeds. The release sends cars to a home area, not to where requests start.","Read the morning wait interval against its margin, then where ready cars wait.","An ops team would check the location of ready cars at release in its own operation.","decision"],
"OPS-05":[6,2,2,"A new East Bay launch opens with 12 cars and a small depot. Would 18 cars serve riders better on the second morning, and can the depot take them?","Only the East Bay fleet changes, 12 to 18 cars. The depot stays at 12 stalls, 1 cleaning bay, 1 service bay. Same riders and 20 paired seeds. No staged delivery or demand ramp.","Read launch rider wait with lot turn-aways and cleaning queues.","An ops team would size a launch depot with the fleet in its own operation.","decision"],
"OPS-06":[6,2,2,"Launch demand arrives 50 percent above plan on a 12 car fleet. What happens to East Bay riders, and to the area next door?","Only East Bay peak demand changes, 30 to 45 requests an hour; fleet and depot stay small. Same seeds. Dispatch sends the nearest idle car, so cars cross area lines. A stress test, not a decision.","Read launch area wait and neighbouring unserved share.","An ops team would write a neighbouring area guardrail before a launch demand test.","condition"],
"OPS-07":[6,2,2,"After the recall, launch cars queue into the night for one cleaning bay. Would 3 bays put more East Bay cars on the road for the second morning?","Only the launch depot bays change, 1 to 3; stalls, fleet and demand stay the same. Same riders, 20 paired seeds that vary travel only. Staff, opening hours and charging are not modeled.","Read when the depot queue happens next to when riders need cars, and where ready cars go overnight.","An ops team would check when a depot queue clears relative to the morning release before buying bays.","decision"],
"OPS-08":[6,2,2,"The launch lot has 6 stalls for 12 cars, so cars get turned away. Would sending every car to the nearest depot with a free stall help East Bay riders?","Only the depot rule changes, home depot to nearest free stall, for the whole fleet. SF-1 and SF-2 are equally near, so ties go to SF-1. Same riders and 20 paired seeds.","Read depot turn-aways and SF-1 bay wait beside East Bay rider wait.","An ops team would test the scope of a depot rule in its own operation.","decision"],
"OPS-09":[2,2,2,"Rain slows roads and wet curbs slow pickups. Does a slower San Francisco curb change the evening peak, and where else does it show up?","In a rain world (slower roads 13:00 to 23:00, more SF requests all day), only SF pickup and short trip time changes, 6 to 9 min, all day. Same riders and 20 paired seeds.","Read whole run unserved share beside the evening wait interval.","An ops team would write a whole run guardrail in its own weather tests.","condition"],
"OPS-10":[1,2,2,"On a rainy day with more San Francisco requests, would 8 extra SF cars serve more riders, and what do they ask of the depots overnight?","In a rain world (slower roads, 2 min longer pickups, about 25 percent more SF requests all day), only the SF fleet changes, 40 to 48 cars. Same riders and 20 paired seeds.","Read whole run unserved share with morning availability, stall blocking and empty driving.","An ops team would test rain demand and road speed separately against its own records.","decision"],
"OPS-11":[4,2,2,"Rain makes each depot clean take 30 minutes, not 20. Does the longer clean reach riders the next morning, or stay inside the depot?","Rain world: slower roads and pickups, more SF requests. One change: clean time 20 to 30 min at every depot. Primary: SF p90 wait, day 2 07:00 to 09:00. Guardrails include available share, 06:00 to 07:00.","Read overnight bay queues and early availability with the morning wait interval.","An ops team would measure cleaning duration against its own overnight queue and readiness window.","condition"],
"OPS-12":[4,2,2,"SF-2 has the longest rain-night queue. Is it where 2 more cleaning bays reach SF riders, or would the same bays at another depot do more?","Rain world with 30 min cleans at every depot. One change: SJ-1 cleaning bays 3 to 5, while SF-2 keeps the longest queue. Primary: SF p90 wait, day 2 07:00 to 09:00.","Read the rider wait interval beside the location of the bay change.","An ops team would compare candidate bay sites on rider service in its own operation.","decision"],
"OPS-13":[2,2,2,"Crowded downtown curbs slow every SF pickup by a car already in SF. Which rider waits feel a 10 minute in-area trip and pickup time instead of 6?","One change: SF in-area trip and pickup time 6 to 10 min, all run. Legs between areas skip it. Primary: SF p90 wait, day 1 07:00 to 09:00. Guardrails: SF unserved share, SF evening wait.","Read morning rider wait beside evening wait and unserved share.","An ops team would test curb changes against its own in-area pickup peaks.","condition"],
"OPS-14":[2,2,2,"A stadium event lets out in SF. Do riders in the East Bay, which shares the same cars, feel the SF surge?","One change: SF peak requests 60 to 90 per hour, day 1 peaks and day 2 morning. The nearest idle car serves any area. Primary: East Bay unserved share, day 1 16:00 to 19:00. Guardrails: EB wait, SF unserved.","Read neighbouring unserved share beside wait and the counted rider population.","An ops team would write an unserved guardrail for neighbouring areas in its own event tests.","condition"],
"OPS-15":[2,2,2,"On an SF event night the East Bay lead adds 8 cars to protect East Bay riders. Do the added cars stay in the East Bay?","Event world: SF at 90 peak requests per hour. One change: East Bay cars 24 to 32, all homed at EB-1. Nearest idle dispatch can send any car anywhere. Primary: East Bay evening unserved share.","Read East Bay unserved share with its depot bay wait and lot peak.","An ops team would log where added cars serve riders and sleep overnight in its own operation.","decision"],
"OPS-16":[2,2,2,"Evening crowds and a street festival slow driving inside every area. Does that show up in wait times, or in riders left unserved?","One change: in-area traffic x1.3 to x2.0, day 1 16:00 to 19:00, in all four areas and on depot entries at once. Primary: map-wide unserved share, day 1 17:00 to 20:00.","Read unserved share by area and rider time in slow traffic.","An ops team would measure each area's unserved share during crowds in its own records.","condition"],
"OPS-17":[0,2,2,"A police closure shuts highway H1 between SF and the Peninsula. How much do Peninsula riders feel it in the morning, when their cars have gone to SF?","One change: H1 from 25 to 90 min, so every SF to Peninsula leg uses local route L1. Depot homes follow route times, so Peninsula cars move to SJ-1. Primary: Peninsula p90 wait, day 1 07:00 to 09:00.","Read Peninsula morning wait and the backup depot's turn-aways.","An ops team would check backup depot stalls and bays against its own closure plans.","condition"],
"OPS-18":[1,2,2,"Police activity keeps 6 of SF's 40 cars at scenes for the whole run. When do SF riders feel it: the same morning or the next?","One change: SF fleet 40 to 34 cars, whole run. Day 1 starts with every car idle at home; day 2 starts where the recall and depot queues left the fleet. Primary: SF p90 wait, day 2 07:00 to 09:00.","Read next morning wait beside neighbouring wait and unserved share.","An ops team would test next morning backfill against its own incident records.","decision"],
"OPS-19":[4,2,2,"After police activity every car needs a service check more often. What does a 45 min service every 2nd depot visit, not every 3rd, do to the next morning?","One change: service every 3rd visit to every 2nd, on the service bays the map has (SF-1 2, SF-2 1, SJ-1 1, EB-1 1). The 00:30 recall sends the fleet through them. Primary: SF p90 wait, day 2 07:00 to 09:00.","Read morning wait, early availability and unfinished depot visits.","An ops team would write a service bay queue guardrail in its own maintenance tests.","decision"],
"OPS-20":[4,2,2,"A police staging area takes 40 of SF-1's 60 stalls all run. Do SF riders feel it next morning, or only the depot gate?","One change: SF-1 stalls 60 to 20. Cars still go to their home depot; a car turned away drives to the nearest depot with a free stall. Primary: SF p90 wait, day 2 07:00 to 09:00. Guardrail: turn-aways, max 0.","Read depot turn-aways alongside the rider wait interval and empty share.","An ops team would write a depot gate guardrail before testing a smaller lot in its own operation.","decision"],
}),...SCALE_LABS.map(l=>[l.id,[8,3,2,...l.frame]])].map(([id,a])=>[id,make(id,a)])));
const surfaceBase=Object.fromEntries(Object.entries({
"day":[3,0,0,"How many ride requests can this fleet complete in an 8 hour day, and what keeps a car from its next rider? The answer points to the lever worth testing.","One synthetic 8 hour day from 07:00 on OpenStreetMap Bay Area roads: requests, pickups, trips, then depot cleaning, charging and upload. One replay per setting, fixed seed. Not calibrated.","Read completed, unserved, waiting and in progress together, then compare fleet and depot sizes to see which one moves completed trips.","An ops team would measure where its own vehicle time goes before buying cars or depot sites."],
"street":[3,1,0,"One constrained street can trap fleet vehicles in road queues. Street lab asks how many rider journeys still finish, and whether routing around the queue helps.","Synthetic traffic on frozen OpenStreetMap SF streets. Each block holds a finite queue, and a full block stops the one behind it. Presets move the hotspot only; Compare runs two route rules on one demand.","Read finished and expired journeys before pickup wait, which averages boarded riders only. Then find where the busiest queues sit.","An ops team would test a routing or pickup change on its own trip records with empty distance as a guardrail."],
"workbench":[3,2,2,"Four schematic Bay Area zones share 120 cars and four depots. Ask one fleet or depot question and see whether rider wait moves, and what it trades.","Invented riders from day 1 05:00 to day 2 10:00, with an overnight recall. An experiment changes one setting, replays the same riders on 20 travel seeds and reads the paired gap.","Read the recommendation with its guardrails, not the main result alone. Each case keeps one set of invented riders.","An ops team would check what a result suggests measuring in its own operation, and not treat it as a reason to change it."],
"four-area":[3,2,0,"Follow one four-area day to see where riders wait and which depot queues, before testing any change.","One replay of the chosen scenario with travel variation at 0, so every replay repeats. Moments mark the peaks, the 00:30 recall and the 05:45 release.","Read rider wait by area and hour next to bay wait by depot and hour, and ask whether the longest queue overlaps a rider peak.","An ops team would map its own waits and depot queues by hour before choosing which constraint to test."],
"regional-power":[3,0,0,"A depot loses part or all of its charging power for 90 minutes mid shift. How many trips does the fleet lose, and can charging order protect service?","Fictional Austin-inspired map, 40 cars, 2 depots, 8 hours. Site A power drops in minutes 90 to 180; Site B keeps 120 kW. Every run also has 1 port per depot out in minutes 60 to 120.","Run each power condition and compare completed and unserved requests, then check whether the charging order comparison moves either.","An ops team would check whether its depots sit at their power cap all day before planning for an event."],
"launch":[3,0,0,"If new charging ports come online 90 minutes late, how much rider service is lost? Launch teams need to know which commissioning dates carry service risk.","Two runs of the chosen template, Peninsula by default or fictional Region B, on the same demand seed: ports commissioned at minute 0 versus minute 90. All else the same. Setup checks are not inspections.","Read completed trips and late or missed pickups first; on time pickups made before the delay window cannot show it.","An ops team would give each port commissioning task an owner and a date, then rehearse a slip against its own peak."],
"reference-panels":[3,2,0,"How does a committed test record read next to a teaching run? These panels quote two outside records so you can compare how a test is written.","Quoted text only: nothing here runs. FLEET-005 is a committed decision record and the two-zone probe is an exploratory run, both from the reference harness, a separate tool whose world differs from this model.","Read each record's question and axis, then the differences list: verdict rules are shared; the world and random draws are not.","An ops team would compare how a record states its question and guardrails with how it writes its own tests."],
"preset:rain":[3,0,0,"Rain at the evening peak slows every trip while more riders ask for one. Which part of the fleet day gives way first: cars, charging or depot work?","Fleet day with three changes at once: start 15:00 instead of 07:00, rain (declared: travel x1.3, energy x1.12, demand x1.12) and base demand 45 requests an hour instead of 30. Fleet and places stay the same. One replay.","Read completed and unserved requests first, then where cars spend time: pickup driving, charging or a depot queue. Three settings change at once.","An ops team would log trip time and requests by weather and hour in its own records."],
"preset:depot":[3,0,0,"One depot serves 32 cars with 1 charger and 1 cleaning bay, and cars visit every 2 trips. Which depot step keeps cars from riders first?","Fleet day with five changes at once: 32 cars instead of 24, 1 depot instead of 2, 1 charger instead of 4, 1 cleaning bay instead of 2, a visit every 2 trips instead of 3. Synthetic demand stays the same. One replay.","Read completed and unserved requests, then the queue minutes at each depot stage to see which step cars wait for. Five settings change at once.","An ops team would log each waiting car's depot step before adding chargers or bays."],
"preset:power":[3,0,0,"Four 80 kW ports share one 40 kW site cap at each depot. When the cap, not the port rating, sets charging speed, how long are cars kept from riders?","Fleet day with four changes at once: 32 cars instead of 24, 80 kW ports instead of 50, 40 kW site power instead of 120, a visit every 2 trips instead of 3. Ports, depots and synthetic demand stay the same. One replay.","Read charging queue minutes and delivered energy next to completed trips, and compare each port's rating with its share of the site cap.","An ops team would compare port ratings with the site cap before adding ports."],
}).map(([id,a])=>[id,make(id,a)]));
surfaceBase["staffing"]={...LESSON_FRAMES["staffing-readiness"],id:"staffing"};
surfaceBase["charging"]={...LESSON_FRAMES["power-redistribution"],id:"charging"};
surfaceBase["deadlines"]={...LESSON_FRAMES["deadline-charging"],id:"deadlines"};
surfaceBase["resources"]={...LESSON_FRAMES["resource-freshness"],id:"resources"};
surfaceBase["airport"]={...LESSON_FRAMES["airport-preparation"],id:"airport"};
surfaceBase["walkthrough"]={...LESSON_FRAMES["OPS-01"],id:"walkthrough"};
surfaceBase["preset:balanced"]={...surfaceBase["day"],id:"preset:balanced"};
surfaceBase["preset:charging"]={...surfaceBase["charging"],id:"preset:charging"};
surfaceBase["preset:resources"]={...surfaceBase["resources"],id:"preset:resources"};
surfaceBase["preset:airport"]={...surfaceBase["airport"],id:"preset:airport"};
surfaceBase["preset:staffing"]={...surfaceBase["staffing"],id:"preset:staffing"};
export const SURFACE_FRAMES=Object.freeze(surfaceBase);
export const GLOSSARY=Object.freeze({
"p90":"p90: 9 in 10 results are at or under this value. A p90 wait of 20 min means at most 1 rider in 10 waited longer.",
"Paired seeds":"Paired seeds: both runs share the same random draws, and the same riders where a model has riders, so a difference comes from the one changed setting.",
"Margin":"Margin: the smallest change in the main result that the test treats as real. It is set before the run.",
"Guardrail":"Guardrail: a measure the change must not harm past its allowance, set before the run. One harmed guardrail stops the change.",
"Allowance":"Allowance (max harm): how far a guardrail may move the wrong way before the change is stopped.",
"Beyond the margin":"Improved or worse beyond the margin: the whole 95% interval sits past the margin on the good or the bad side.",
"Within the margin":"Within the margin: the whole 95% interval sits inside the margin.",
"Crosses the margin":"Interval crosses the margin: the test cannot decide yet.",
"Held":"Held (HOLD): a guardrail or the main result went the wrong way past its limit. For a condition nobody chooses, it means the condition harms service.",
"Advance":"Advance to the next test: the main result improved and every evaluated guardrail stayed within its allowance. The next step is another simulation test.",
"No recommendation":"No recommendation: nothing moved beyond the margin. It is not proof that the change has no effect.",
"Unserved":"Unserved: a rider with no car assigned within the patience time, who then left.",
"Waiting, in progress":"Waiting and in progress: requests still open when the run ends. They are counted, not dropped.",
"One replay":"One replay: a single run on one seed. It describes one day and cannot tell noise from an effect.",
"Same riders":"Same riders: in Four-area experiments, each case keeps one fixed set of invented riders; seeds vary travel times only. Another set of riders can change a call.",
"Empty distance":"Empty distance: km driven with no rider on board, to reach a pickup or a depot.",
"Recall, release":"Recall and release: at day 2 00:30 idle cars head to their depot. At 05:45 ready cars outside their home area drive home.",
"NOT_EVIDENCE":"NOT_EVIDENCE: every number is invented teaching output from an uncalibrated model, not a measurement of any fleet.",
"Null control":"Null control: both arms get the same setup, so every paired difference is zero by construction. If it reads otherwise, the test is broken.",
"Governing ratio":"Governing ratio: load over capacity, or a lag over the interval between arrivals, that decides whether a mechanism shows. The lab derives the other inputs.",
});
export const CASEBOOK_READINGS=Object.freeze({
"OPS-01":{"labels":["playground-spec:089edeff","playground-spec:0e605b63","playground-spec:5f23aed6"],"outcome":"IMPROVED","recommendation":"HOLD","template":"Seed set {set}: SF evening wait p90 fell {primary:min} min while SF-2 bay wait p90 rose {g1:min} min, past its 30 min allowance, so the call is HOLD. SF wait p90 the next morning also fell {g2:min} min, inside its allowance."},
"OPS-02":{"labels":["playground-spec:5e6da8a7","playground-spec:05bdb4df","playground-spec:498421c4"],"outcome":"IMPROVED","recommendation":"ADVANCE_TO_NEXT_TEST","template":"Seed set {set}: a 02:00 recall gives late night SF riders pickups {primary:min} min faster (p50); SF-2 bay wait p90 rises {g2:min} min, inside its 30 min limit."},
"OPS-03":{"labels":["playground-spec:bea8dbfd","playground-spec:5572b64c","playground-spec:2614682e"],"outcome":"IMPROVED","recommendation":"ADVANCE_TO_NEXT_TEST","template":"Seed set {set}: every 15 trips serves {primary:pts} more of every 100 SF evening requests, and SF-2 bay wait p90 rises {g2:min} min, inside its 30 min limit for this set of riders."},
"OPS-04":{"labels":["playground-spec:4134c2a4","playground-spec:d6eb0885","playground-spec:48329077"],"outcome":"INCONCLUSIVE","recommendation":"RUN_MORE_EXPERIMENTS","template":"Seed set {set}: with a 05:00 release, SF morning wait p90 rises {primary:s} s for this set of riders; its interval sits above zero but straddles the 30 s margin. An earlier release is not earlier readiness here."},
"OPS-05":{"labels":["playground-spec:bfaabbfa","playground-spec:dab153ca","playground-spec:3255540f"],"outcome":"IMPROVED","recommendation":"HOLD","template":"Seed set {set}: 6 more cars shorten East Bay morning wait p90 by {primary:min} min, but the 12 stall, one bay depot turns away {g2:n} cars a run and its bay wait p90 rises {g3:min} min."},
"OPS-06":{"labels":["playground-spec:c35d4d31","playground-spec:10b668b8","playground-spec:a0541932"],"outcome":"REGRESSED","recommendation":"HOLD","template":"Seed set {set}: at 45 requests an hour East Bay morning wait p90 rises {primary:min} min, and San Francisco leaves {g2:pts} more of every 100 riders unserved, past its 1 point limit."},
"OPS-07":{"labels":["playground-spec:33571abe","playground-spec:f6b61daf","playground-spec:19ff7217"],"outcome":"INCONCLUSIVE","recommendation":"RUN_MORE_EXPERIMENTS","template":"Seed set {set}: 3 bays cut EB-1 bay wait p90 by {g1:min} min, yet East Bay morning wait shows no clear benefit: its interval crosses the margin."},
"OPS-08":{"labels":["playground-spec:f6c229cb","playground-spec:4e233d46","playground-spec:e23a5f98"],"outcome":"INCONCLUSIVE","recommendation":"HOLD","template":"Seed set {set}: turn-aways fall from {b.depot.diversions:n} to {c.depot.diversions:n} a run, but SF-1 takes the San Francisco night wave: its bay wait p90 rises {g3:min} min, while East Bay riders see no clear change."},
"OPS-09":{"labels":["playground-spec:70a21ebe","playground-spec:e205d813","playground-spec:c1610927"],"outcome":"INCONCLUSIVE","recommendation":"HOLD","template":"Seed set {set}: 9 min pickups leave the SF evening wait tail with no clear change, but whole run unserved rises {g1:pts} points, past its 1 point limit."},
"OPS-10":{"labels":["playground-spec:22831304","playground-spec:13ac6662","playground-spec:58425b5a"],"outcome":"IMPROVED","recommendation":"ADVANCE_TO_NEXT_TEST","template":"Seed set {set}: 8 more cars lower whole run unserved by {primary:pts} points, with every guardrail inside its limit: 06:00 to 07:00 availability, SF-2 stall blocking and empty driving."},
"OPS-11":{"labels":["playground-spec:c23a8ba8","playground-spec:63880b85","playground-spec:baa03fc0"],"outcome":"INCONCLUSIVE","recommendation":"HOLD","template":"On 3 seed sets: no clear shift in SF morning wait, while SF-2 bay wait and the 06:00 to 07:00 available share pass their limits."},
"OPS-12":{"labels":["playground-spec:1505ff49","playground-spec:7fecb9d9","playground-spec:76e152c8"],"outcome":"IMPROVED","recommendation":"ADVANCE_TO_NEXT_TEST","template":"Seed set {set}: 2 more bays at SJ-1 lower SF morning p90 wait by {primary:min} min, with every guardrail inside its limit."},
"OPS-13":{"labels":["playground-spec:83a51e1f","playground-spec:ab441f9f","playground-spec:41406fbc"],"outcome":"REGRESSED","recommendation":"HOLD","template":"Seed set {set}: SF morning p90 wait {primary:min} min higher; the evening wait stays inside its 2 min limit."},
"OPS-14":{"labels":["playground-spec:cec780af","playground-spec:5aed180d","playground-spec:38a4a490"],"outcome":"REGRESSED","recommendation":"HOLD","template":"Seed set {set}: East Bay leaves {primary:pts} more of every 100 evening requests unserved, while its p90 wait stays inside its 2 min limit. A rider with no car in 10 min leaves and is not in the wait."},
"OPS-15":{"labels":["playground-spec:f06dffe7","playground-spec:550c3ac5","playground-spec:be053df4"],"outcome":"IMPROVED","recommendation":"HOLD","template":"Seed set {set}: East Bay evening unserved falls {primary:pts} points and SF unserved falls too, while EB-1 bay wait and lot peak pass their limits."},
"OPS-16":{"labels":["playground-spec:607e34c7","playground-spec:218dca0b","playground-spec:b587f2b2"],"outcome":"REGRESSED","recommendation":"HOLD","template":"Seed set {set}: {primary:pts} more of every 100 riders unserved map-wide in the evening, and more rider time in slow traffic; SF p90 wait shows no steady direction across the 3 seed sets."},
"OPS-17":{"labels":["playground-spec:1b429508","playground-spec:7dd66842","playground-spec:28523621"],"outcome":"REGRESSED","recommendation":"HOLD","template":"Seed set {set}: Peninsula morning p90 wait {primary:min} min higher, and SJ-1, where Peninsula cars now sleep, turns {g3:n} cars away per run."},
"OPS-18":{"labels":["playground-spec:a940e907","playground-spec:27ea3003","playground-spec:b0f5b629"],"outcome":"REGRESSED","recommendation":"HOLD","template":"Seed set {set}: SF p90 wait on the day 2 morning is {primary:min} min higher."},
"OPS-19":{"labels":["playground-spec:f1a88379","playground-spec:aa8704fa","playground-spec:8c0aa652"],"outcome":"REGRESSED","recommendation":"HOLD","template":"Seed set {set}: SF morning p90 wait {primary:min} min higher and 06:00 to 07:00 availability {g2:pts} points lower, while cleaning bay wait moves under 1 min."},
"OPS-20":{"labels":["playground-spec:800a66ff","playground-spec:5c47490c","playground-spec:2c0c07f3"],"outcome":"UNCHANGED","recommendation":"HOLD","template":"Seed set {set}: SF morning wait stays inside its 1 min band, while {g1:n} cars per run are turned away at SF-1. Only the zero-limit gate guardrail sees it."},
});
export const OUTCOME_WORDS=Object.freeze({IMPROVED:'Improved beyond the margin',REGRESSED:'Worse beyond the margin',UNCHANGED:'Within the margin',INCONCLUSIVE:'Interval crosses the margin, not decided'});
export const NEXT_TEST=Object.freeze({guardrail:'Relieve {guardrail} as its own change, then retry this one with both declared.',primary:'Keep the current setting and look for the resource this change took time from.',improved:'Repeat on another seed set and another rider draw, then read measures no guardrail covered.',inconclusive:'Add paired seeds or test a larger step of the same setting.',unchanged:'Check whether the queue this change relieved held cars riders needed, then test the resource that did.',invalid:'Fix the invalid run first.'});
const absent='not available: no recorded value';
const num=(v,d=1)=>Number.isFinite(v)?(v!==0&&Number(v.toFixed(d))===0?String(v):v.toFixed(d)):absent;
const sign=v=>Number.isFinite(v)?(v>0?'+':'')+num(v):absent;
const upper=s=>s[0]?.toUpperCase()+s.slice(1);
export function evidenceText(frame,n){return frame.evidence==='paired'?Number.isInteger(n)?`Paired test, ${n} seeds`:'Paired test, seed count not available':frame.evidence==='one-seed'?'One seed, same demand':'One replay';}
export function glossaryView(){return el('details',{class:'teaching-glossary'},[el('summary',{},'Words used here'),...Object.values(GLOSSARY).map(text=>el('p',{},text))]);}
export function exactView(value,children=[]){return el('details',{class:'teaching-exact'},[el('summary',{},'Exact values'),...children,el('p',{},'Harm is signed so that a negative value means the candidate did better.'),el('pre',{},JSON.stringify(value,null,2))]);}
let exactSerial=0;
export function exactDisclosure(children){const id='teaching-exact-'+(++exactSerial),body=el('div',{id,hidden:true},children),button=el('button',{type:'button','aria-expanded':'false','aria-controls':id,on:{click:()=>{body.hidden=!body.hidden;button.setAttribute('aria-expanded',String(!body.hidden));}}},'Exact values');return el('section',{class:'teaching-exact'},[button,body]);}
function annotated(text,seen){const parts=[];const re=/\bp90\b|\bpaired seeds\b|\bguardrail\b|\bmargin\b|\bunserved\b|\bempty distance\b/gi;let start=0;for(const m of text.matchAll(re)){const key=Object.keys(GLOSSARY).find(k=>k.toLowerCase()===m[0].toLowerCase());if(!key||seen.has(key))continue;parts.push(text.slice(start,m.index),el('abbr',{title:GLOSSARY[key]},m[0]));seen.add(key);start=m.index+m[0].length;}parts.push(text.slice(start));return parts;}
export function frameView(frame,view={}){
 const seen=new Set();const a=text=>annotated(text,seen);
 const f=frame??{what_why:absent,how:absent,look_for:absent,ops_takeaway:absent};
 return el('section',{class:'teaching-frame','data-frame':f.id??'unavailable'},[
  el('div',{class:'teaching-heading'},[view.titleNode??el(view.heading??'h2',{class:'teaching-title'},view.title??f.title??f.id??'Lesson'),el('div',{class:'teaching-chips'},[f.family,f.model,evidenceText(f,view.seeds),...(f.kind?[f.kind==='condition'?'Condition test':'Decision test']:[])].filter(Boolean).map(t=>el('span',{},t+' ')))]),
  el('div',{class:'teaching-parts'},[['What & why',[el('p',{},a(f.what_why))]],['How we simulate',[el('p',{},a(f.how)),...(view.change?[el('p',{class:'teaching-change'},view.change)]:[])]],['Learning & ops takeaway',[el('p',{},[el('strong',{},'What to look for: '),...a(f.look_for)]),el('p',{},[el('strong',{},'Ops takeaway to test: '),...a(f.ops_takeaway)])]]].map(([label,body],i)=>el('div',{'data-part':String(i+1)},[el('h3',{},label),...body]))),
  view.edited?el('p',{class:'teaching-edited'},'Setup changed from this lesson. The frame still describes the lesson setup.'):null,
  el('details',{class:'teaching-limits'},[el('summary',{},'Limits and what this misses'),...(view.limits||f.limits!==make('',[0,0,0]).limits?[el('p',{},view.limits??f.limits??absent)]:[]),el('p',{},'Each model has its own assumptions, so numbers from different models are not interchangeable.')]),
 ]);
}
/** Display arithmetic over recorded fields; never consumes frames or logs. `tools.sided` is a page that asks for numbers
 * kept on their side of the margin and for a line that keeps its interval: it drops the guardrail sentence first. */
export function runLine(frame,r,tools={}){
 const words=tools.words??(key=>String(key??'Main result').replaceAll('_',' '));
 const n=tools.number??num,s=tools.signed??sign,NEXT=tools.next??NEXT_TEST;
 const result=(line,next=null)=>({line,next});
 if(!r||r.validity?.startsWith('INVALID'))return result(`Invalid run: ${r?.reason??r?.invalidityReason??'required result unavailable'}. No result can be read.`,NEXT.invalid);
 if(r.type==='replay'||r.type==='street'){
  const m=r.metrics??{},keys=r.type==='street'?['completed','requests','expired','waiting','in_progress']:['completed_trips','total_requests','unserved_requests','pending_requests','in_progress_trips'];
  const v=keys.map(k=>m[k]);if(v.some(x=>!Number.isFinite(x)))return result('Run counts not available: the request partition was not recorded.');
  return result(`${v[0]} of ${v[1]} ${r.type==='street'?'journeys finished':'requests completed'} in this replay; ${v[2]} ${r.type==='street'?'expired':'unserved'}, ${v[3]} waiting and ${v[4]} in progress at the end. Seed ${r.seed}, one replay.`);
 }
 if(r.type==='austin')return result(`${r.metrics.completed_trips} of ${r.metrics.total_requests} requests completed and ${r.metrics.unserved_requests} unserved; plugged-in cars got 0 kW for ${n(r.zeroPower,0)} vehicle-min. ${r.condition}, seed ${r.seed}, one replay.`);
 if(r.type==='launch'){
  const d=r.comparison.deltas,a=r.baseline.launch.metrics,b=r.candidate.launch.metrics;
  return result(`Seed ${r.spec.seed}, ${r.template} template: commissioning ${r.spec.delay_minutes} min late changed completed trips by ${s(d.completed_trips,0)} (${a.completed_trips} to ${b.completed_trips}), late pickups by ${s(d.pickup_late,0)}, missed pickups by ${s(d.pickup_missed,0)} and on time pickups by ${s(d.pickup_within_target,0)}${d.pickup_within_target?` (${a.pickup_within_target} to ${b.pickup_within_target})`:''}. One seed; descriptive.`);
 }
 if(r.type==='staffing'){
  const a=r.arms,m=a[0].result.metrics,b=a[0].result.readiness.metrics.blocked_minutes;
  return result(`Seed ${r.seed_set[0]}, ${r.horizon_minutes} min: baseline ${m.completed_trips} of ${m.total_requests} trips, one more worker ${a[1].result?.metrics.completed_trips??absent}, one more bay ${a[2].result?.metrics.completed_trips??absent}. Queued clean minutes: no free worker ${n(b.WORKER_UNAVAILABLE,0)}, no free bay ${n(b.BAY_UNAVAILABLE,0)}, both ${n(b.BAY_AND_WORKER_UNAVAILABLE,0)}. One seed; descriptive.`);
 }
 if(r.type==='text')return result(r.line);
 const p=r.primary,guards=r.guardrails??[];
 if(!p||!Number.isFinite(p.mean_delta))return result('One seed is descriptive; no interval or recommendation.');
 const bad=guards.filter(g=>g.status==='REGRESSED'),missing=guards.filter(g=>g.status==='NOT_EVALUABLE');
 const reason=bad.length?'guardrail':r.outcome==='REGRESSED'?'primary':r.outcome==='IMPROVED'?'improved':r.outcome==='INCONCLUSIVE'?'inconclusive':'unchanged';
 const metric=p.metric,margin=p.equivalence_margin??r.margin;
 const value=(v,threshold=false)=>{
  if(!Number.isFinite(v))return absent;
  if(String(metric).split('{')[0].endsWith('_s')&&margin>=60){const rounded=Number(n(v/60,1))*60;if(Number(n(margin/60,1))*60===margin&&[-margin,0,margin].every(t=>Math.sign(v-t)===Math.sign(rounded-t)))return (threshold?n(v/60,1):s(v/60,1))+' min';return (v>0&&!threshold?'+':'')+v+' s';}
  return threshold?(tools.threshold?.(metric,v)??n(v)):(tools.metricValue?.(metric,v,tools.sided?{withSign:true,against:margin>0?[-margin,margin]:[]}:{withSign:true})??s(v));
 };
 let primary=`${OUTCOME_WORDS[r.outcome]??'Result not decided'}: ${words(metric)} ${value(p.mean_delta)} (95% interval ${value(p.ci_low)} to ${value(p.ci_high)}; margin ${value(margin,true)}).`;
 let rail=bad.length?bad.map(g=>`${upper(words(g.metric))} went past its allowance.`).join(' '):guards.length&&!missing.length?'Every guardrail stayed within its allowance.':guards.length?'':'No guardrails were declared.';
 if(missing.length)rail+=` ${missing.length} guardrail${missing.length===1?'':'s'} not available: ${missing[0].reason??'required population missing'}.`;
 let recommendation=r.recommendation==='HOLD'?frame.kind==='condition'?'Held: this condition harms service past an allowance.':reason==='guardrail'?'Held because a guardrail went past its allowance.':'Held because the main result regressed.':r.recommendation==='ADVANCE_TO_NEXT_TEST'?'Advance to the next simulation test, not a rollout.':r.recommendation==='RUN_MORE_EXPERIMENTS'?tools.more??'Run more paired seeds before reading a direction.':'No recommendation: nothing moved beyond the margin.';
 let line=()=>`${primary} ${rail} ${recommendation}`.replace(/\s+/g,' ').trim();
 if(line().length>240&&bad.length)rail=`${bad.length} guardrail${bad.length===1?' went past its allowance':'s went past their allowances'}; see the guardrail table.`;
 if(line().length>240&&bad.length&&r.recommendation==='HOLD'){
  if(frame.kind==='condition'){rail='';recommendation=`Held: this condition harms service past ${bad.length===1?'an allowance':bad.length+' allowances'}; see the guardrail table.`;}else recommendation='Held.';
 }
 if(tools.sided&&line().length>240)rail='';
 if(line().length>240)primary=`${OUTCOME_WORDS[r.outcome]??'Result not decided'}: ${words(metric)} ${value(p.mean_delta)}; interval and margin under Exact values.`;
 return result(line(),NEXT[reason].replace('{guardrail}',bad.length?words(bad[0].metric):'the affected measure'));
}
export function casebookReading(frame,r,tools={}){
 const read=CASEBOOK_READINGS[frame.id];if(!read||r.validity!=='VALID'||read.outcome!==r.outcome||read.recommendation!==r.recommendation)return null;
 const set=read.labels.indexOf(r.label)+1;if(!set)return null;
 let unavailable=false;
 const filled=read.template.replace(/\{([^}]+)\}/g,(_,slot)=>{
  if(slot==='set')return String(set);
  const [name,unit]=slot.split(':');let v;
  if(name==='primary')v=r.primary?.mean_delta;
  else if(/^g\d+$/.test(name))v=r.guardrails?.[Number(name.slice(1))-1]?.harm;
  else{const d=r.descriptives?.find(d=>d.metric===name.slice(2));v=d?.[name[0]==='b'?'baseline_mean':'candidate_mean'];}
  if(!Number.isFinite(v)){unavailable=true;return absent;}
  v=Math.abs(v)*(unit==='min'?1/60:unit==='pts'?100:1);
  return tools.nonzero?tools.nonzero(v,1):num(v,1);
 });
 return unavailable||filled.length>240?null:filled;
}
export function resultView(frame,result,tools={}){
 const reading=casebookReading(frame,result,tools),run=runLine(frame,result,tools);
 return el('section',{class:'teaching-result'},[el('h3',{},'What this run shows'),el('p',{class:'teaching-run-line'},run.line),run.next?el('div',{},[el('h4',{},'Next test to try'),el('p',{},run.next)]):null,el('h4',{},'Ops takeaway to test'),el('p',{},frame.ops_takeaway),reading?el('div',{class:'casebook-reading'},[el('h4',{},'Casebook reading, checked by tests'),el('p',{},reading)]):null]);
}
