import * as ml from './vendor/maplibre-gl.mjs';
const BOX = [[-122.519, 37.708], [-122.353, 37.834]];
const empty = () => ({type:'FeatureCollection',features:[]});
const make = (tag, cls, text) => { const e=document.createElement(tag);e.className=cls;if(text)e.textContent=text;return e; };
export class CityMap {
  constructor(host, roads, geometry, {flat=false, replay=false, onInspect=()=>{}}={}) {
    Object.assign(this,{host,roads,geometry,replay,onInspect,sites:[],markers:[],routes:empty(),mask:'support',flat,center:[-122.436,37.77],zoom:11.6});
    this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);
    if(flat){this.useFlat();return;}
    try {
      ml.setWorkerUrl(new URL('./vendor/maplibre-gl-worker.mjs',import.meta.url).href);
      this.map=new ml.Map({container:host,center:this.center,zoom:11.6,minZoom:10,maxZoom:20,attributionControl:false,
        style:{version:8,sources:{land:{type:'geojson',data:{type:'Feature',geometry:geometry.land,properties:{}}},roads:{type:'geojson',data:roads,maxzoom:20,tolerance:.1},route:{type:'geojson',data:empty()}},layers:[
          {id:'water',type:'background',paint:{'background-color':'#e0eee8'}},
          {id:'land',source:'land',type:'fill',paint:{'fill-color':'#f7f5e9'}},
          {id:'road-casing',source:'roads',type:'line',filter:['!=',['get','status'],'excluded'],paint:{'line-color':'#d8dfcf','line-width':['interpolate',['linear'],['zoom'],10,.8,14,3,18,18,20,48]}},
          {id:'roads',source:'roads',type:'line',filter:['!=',['get','status'],'excluded'],paint:{'line-color':replay?'#fbfcf6':['match',['get','status'],'unsupported','#bb8b44','excluded','#b8c2b4','#77a392'],'line-width':['interpolate',['linear'],['zoom'],10,.4,14,1.5,18,13,20,40]}},
          {id:'route',source:'route',type:'line',paint:{'line-color':['match',['get','purpose'],'passenger','#306ca3','returning','#b17530','#69755a'],'line-width':['interpolate',['linear'],['zoom'],10,2,16,4,20,7],'line-opacity':.8}},
          {id:'street-names',source:'roads',type:'symbol',minzoom:14,filter:['all',['!=',['get','name'],'Unnamed road'],['!=',['get','status'],'excluded']],layout:{'symbol-placement':'line','text-field':['get','name'],'text-font':['Arial'],'text-size':['interpolate',['linear'],['zoom'],14,12,18,15],'symbol-spacing':320},paint:{'text-color':'#4a6052','text-halo-color':'#fffdf4','text-halo-width':2}}
        ]}});
      this.map.addControl(new ml.NavigationControl({showCompass:false}),'top-right');
      this.map.addControl(new ml.ScaleControl({unit:'imperial'}),'bottom-left');
      this.map.on('load',()=>{this.ready=true;this.map.resize();this.map.fitBounds(BOX,{padding:30,duration:0});this.setRoutes(this.routes);this.setSites(this.sites);this.setMask(this.mask);this.setScenario(this.scenario??[]);if(this.fitPending)this.fitRoute();});
      this.map.on('click','roads',e=>{const p=e.features[0].properties;onInspect(`${p.name} · ${p.class} · ${p.status}. Snapshot geometry; access is not verified.`);});
      this.map.getCanvas().addEventListener('webglcontextlost',e=>{e.preventDefault();this.useFlat();});
      this.map.on('error',()=>onInspect('Map rendering encountered a problem. Use the flat map if streets are unavailable.'));
    } catch { this.useFlat(); }
  }
  setRoads(roads){this.roads=roads;this.map?.getSource('roads')?.setData(roads);this.drawFlat();}
  setMask(mask){this.mask=mask;if(this.ready){for(const id of ['roads','road-casing'])this.map.setFilter(id,mask==='source'?null:['!=',['get','status'],'excluded']);this.map.getSource('points')?.setData(empty());}this.drawFlat();}
  setScenario(points){this.scenario=points;if(this.ready&&!this.map.getSource('points')){this.map.addSource('points',{type:'geojson',data:empty()});this.map.addLayer({id:'points',source:'points',type:'circle',paint:{'circle-radius':3,'circle-color':'#4d70a1'}});}if(this.ready)this.map.getSource('points').setData({type:'FeatureCollection',features:points.map(coordinates=>({type:'Feature',geometry:{type:'Point',coordinates},properties:{}}))});this.drawFlat();}
  setSites(sites){this.sites=sites;for(const m of this.markers)m.remove();this.markers=[];if(this.map){for(const site of sites){const el=make('div','depot-marker',site.id);el.setAttribute('role','img');el.setAttribute('aria-label',`Fictional depot ${site.id}`);el.title=`Fictional depot ${site.id}`;this.markers.push(new ml.Marker({element:el}).setLngLat(site.coordinates).addTo(this.map));}}this.drawFlat();}
  setRoutes(routes){this.routes=routes;this.map?.getSource('route')?.setData(routes);this.drawFlat();}
  setCar(sample){if(this.sample===sample)return;this.sample=sample;if(this.map){if(!this.car){const el=make('div','vehicle-map-marker');this.carIcon=make('span','vehicle-map-icon','↑');el.append(this.carIcon);el.setAttribute('role','img');el.setAttribute('aria-label','Selected vehicle, enlarged symbol');this.car=new ml.Marker({element:el}).setLngLat([0,0]).addTo(this.map);}this.car.getElement().hidden=!sample;if(sample){this.car.setLngLat([sample[1],sample[2]]);this.carIcon.style.transform=`rotate(${sample[3]}deg)`;}}this.drawFlat(true);}
  fit(){if(this.map)this.map.fitBounds(BOX,{padding:35,duration:0});else{this.center=[-122.436,37.77];this.zoom=11.6;this.drawFlat();}}
  fitRoute(){this.fitPending=true;const coords=this.routes.features.flatMap(f=>f.geometry.coordinates);if(!coords.length){this.fit();return;}const box=[[Math.min(...coords.map(p=>p[0])),Math.min(...coords.map(p=>p[1]))],[Math.max(...coords.map(p=>p[0])),Math.max(...coords.map(p=>p[1]))]];if(this.ready){this.map.fitBounds(box,{padding:65,maxZoom:16,duration:0});this.fitPending=false;}else if(this.flat){this.center=[(box[0][0]+box[1][0])/2,(box[0][1]+box[1][1])/2];const scale=Math.min((this.host.clientWidth-100)/Math.max(.0001,box[1][0]-box[0][0]),(this.host.clientHeight-100)*Math.cos(this.center[1]*Math.PI/180)/Math.max(.0001,box[1][1]-box[0][1]));this.zoom=Math.max(10,Math.min(16,Math.log2(scale*360/256)));this.drawFlat();}}
  focusCar(){if(!this.sample)return;if(this.map)this.map.jumpTo({center:[this.sample[1],this.sample[2]],zoom:16.5});else{this.center=[this.sample[1],this.sample[2]];this.zoom=16;this.drawFlat();}}
  resize(){this.map?.resize();this.drawFlat();}
  useFlat(){this.map?.remove();this.map=null;this.ready=false;this.flat=true;this.car=null;this.markers=[];this.host.replaceChildren();this.canvas=make('canvas','flat-canvas');this.canvas.tabIndex=0;this.canvas.setAttribute('aria-label','Flat street map. Arrow keys pan; plus and minus zoom.');this.host.append(this.canvas);const controls=make('div','flat-controls');for(const [label,step]of [['Zoom in',1],['Zoom out',-1]]){const b=make('button','',step>0?'+':'−');b.setAttribute('aria-label',label);b.onclick=()=>{this.zoom=Math.max(10,Math.min(20,this.zoom+step));this.drawFlat();};controls.append(b);}this.host.append(controls);let drag;
    this.canvas.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];this.canvas.setPointerCapture(e.pointerId);});
    this.canvas.addEventListener('pointermove',e=>{if(!drag)return;const scale=this.scale();this.center[0]-=(e.clientX-drag[0])/scale;this.center[1]+=(e.clientY-drag[1])/(scale/Math.cos(this.center[1]*Math.PI/180));drag=[e.clientX,e.clientY];this.drawFlat();});
    this.canvas.addEventListener('pointerup',()=>{drag=null;});this.canvas.addEventListener('pointercancel',()=>{drag=null;});
    this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(10,Math.min(20,this.zoom-Math.sign(e.deltaY)*.3));this.drawFlat();},{passive:false});
    this.canvas.addEventListener('keydown',e=>{const d=40/this.scale();if(['+','=','-','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();if(['+','='].includes(e.key))this.zoom=Math.min(20,this.zoom+1);if(e.key==='-')this.zoom=Math.max(10,this.zoom-1);if(e.key==='ArrowLeft')this.center[0]-=d;if(e.key==='ArrowRight')this.center[0]+=d;if(e.key==='ArrowUp')this.center[1]+=d;if(e.key==='ArrowDown')this.center[1]-=d;this.drawFlat();});this.onInspect('Flat renderer active · drag to pan, + / − to zoom. Same source roads.');this.drawFlat();}
  scale(){return 256*2**this.zoom/360;}
  drawFlat(onlyVehicle=false){if(!this.flat||!this.canvas)return;const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;const ratio=Math.min(devicePixelRatio,2);this.canvas.width=w*ratio;this.canvas.height=h*ratio;this.canvas.style.width=`${w}px`;this.canvas.style.height=`${h}px`;const ctx=this.canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.fillStyle='#e0eee8';ctx.fillRect(0,0,w,h);const scale=this.scale();const xy=p=>[(p[0]-this.center[0])*scale+w/2,(this.center[1]-p[1])*scale/Math.cos(this.center[1]*Math.PI/180)+h/2];const path=points=>{ctx.beginPath();points.forEach((p,i)=>{const [x,y]=xy(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});};const polys=this.geometry.land.type==='MultiPolygon'?this.geometry.land.coordinates:[this.geometry.land.coordinates];ctx.fillStyle='#f7f5e9';for(const polygon of polys){ctx.beginPath();for(const ring of polygon)ring.forEach((p,i)=>{const [x,y]=xy(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.fill('evenodd');}
    if(onlyVehicle&&this.flatBackground){ctx.drawImage(this.flatBackground,0,0,w,h);}else{
    const labels=new Set(),labelBoxes=[];for(const f of this.roads.features){const p=f.properties;if(this.mask!=='source'&&p.status==='excluded')continue;const coords=f.geometry.coordinates;ctx.strokeStyle=p.status==='unsupported'?'#bb8b44':this.replay?'#c5d4c7':'#77a392';ctx.lineWidth=Math.min(10,Math.max(.5,(this.zoom-10)*.55));path(coords);ctx.stroke();if(this.zoom>=14&&!labels.has(p.name)&&p.name!=='Unnamed road'){const [x,y]=xy(coords[Math.floor(coords.length/2)]);const cell=`${Math.floor(x/120)},${Math.floor(y/40)}`;const box=[x-4,y-16,x+p.name.length*7+8,y+6];if(x>30&&x<w-70&&y>30&&y<h-20&&box[2]<w-10&&!labels.has(cell)&&!labelBoxes.some(b=>box[0]<b[2]&&box[2]>b[0]&&box[1]<b[3]&&box[3]>b[1])){ctx.font='12px sans-serif';ctx.lineWidth=3;ctx.strokeStyle='#fffdf4';ctx.strokeText(p.name,x,y);ctx.fillStyle='#4a6052';ctx.fillText(p.name,x,y);labels.add(p.name);labels.add(cell);labelBoxes.push(box);}}}
    for(const f of this.routes.features){path(f.geometry.coordinates);ctx.strokeStyle=f.properties.purpose==='passenger'?'#306ca3':f.properties.purpose==='returning'?'#b17530':'#69755a';ctx.lineWidth=3;ctx.stroke();}
    for(const p of this.mask==='scenario'?(this.scenario??[]):[]){const[x,y]=xy(p);ctx.fillStyle='#4d70a1';ctx.fillRect(x-2,y-2,4,4);}
    for(const s of this.sites){const[x,y]=xy(s.coordinates);ctx.fillStyle='#ad4140';ctx.fillRect(x-13,y-13,26,26);ctx.fillStyle='white';ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillText(s.id,x,y+5);ctx.textAlign='left';}
    this.flatBackground??=document.createElement('canvas');this.flatBackground.width=this.canvas.width;this.flatBackground.height=this.canvas.height;this.flatBackground.getContext('2d').drawImage(this.canvas,0,0);}
    if(this.sample){const[x,y]=xy([this.sample[1],this.sample[2]]);ctx.save();ctx.translate(x,y);ctx.rotate(this.sample[3]*Math.PI/180);ctx.fillStyle='#24483d';ctx.fillRect(-8,-15,16,30);ctx.fillStyle='#fff8df';ctx.fillRect(-5,-9,10,9);ctx.restore();}
  }
}
