import assert from 'node:assert/strict';
import {test} from 'node:test';
import {installFakeDom} from './helpers/fake-dom.mjs';
import {createOperationsLab} from '../src/ui/operations-lab.js';
import {createStreetLab} from '../src/ui/street-lab.js';
const H3=/\b(predict(?:s|ed|ing|ion|ions|ive)?|forecast(?:s|ed|ing|er|ers)?|expected\s+traffic|live|real[\s-]?time|monitoring)\b/i;
const H6=/\b(wins?|winners?|beats|scores?|scoring|gauges?|grades?|leaderboards?|revenue|costs?)\b|better option|best configuration/i;
export function humanCopy(node){if(node.localName==='pre'&&node.parentElement?.localName==='details'&&node.parentElement.querySelector('summary')?.textContent==='Exact values'&&!node.parentElement.hasAttribute('open'))return '';return node.children?.length?[...node.childNodes].map(n=>n.nodeType===3?n.textContent:humanCopy(n)).join(' '):node.textContent;}
function check(node){const text=humanCopy(node);for(const re of [H3,H6,/[\u2013\u2014]/]){const match=re.exec(text);assert.ok(!match,match?text.slice(Math.max(0,match.index-80),match.index+120):'');}}
test('Fleet day and Street readable UI exclude forbidden claims including runtime policy names',()=>{const restore=installFakeDom();const ops=createOperationsLab(),street=createStreetLab();try{check(ops.element);check(street.element);}finally{ops.destroy();street.destroy();restore();}});
import {mountStudio} from '../src/ui/studio.js';
import {createStore,createInitialState} from '../src/ui/store.js';
import {defaultScenario} from '../src/model/schema.js';
import {renderReferencePanel,renderVerdictCard,verdictView} from '../src/ui/experiment.js';
import {PRESETS} from '../src/model/presets.js';
import {freezeSpec,runExperimentSpec} from '../src/model/experiment.js';
import {createLaunchPanel} from '../src/ui/launch-view.js';
import {advancedOperationsDemoConfig} from '../src/model/bay-experiment-contract.js';
test('all mounted shell surfaces, quoted panels and a real paired result keep readable copy within the copy rules',()=>{const restore=installFakeDom();const root=document.createElement('div');document.body.appendChild(root);const studio=mountStudio({root,store:createStore(createInitialState({presetId:'bay_teaching_map',scenario:defaultScenario()})),playback:{pause(){}},present:{open(){},close(){}}});try{check(studio.element);for(const id of ['fleet005','probe'])check(renderReferencePanel(id,{}));const frozen=freezeSpec(PRESETS.find(p=>p.id==='OPS-01').experiment);check(renderVerdictCard(verdictView(runExperimentSpec(frozen.spec),frozen)));}finally{studio.destroy();restore();}});
test('all eight Fleet day situations, runtime policies and invalid launch remain readable',async()=>{const restore=installFakeDom(),lab=createOperationsLab();try{const choose=lab.element.querySelector('[aria-label="Start with a situation"]');for(const option of [...choose.querySelectorAll('option')].filter(o=>!o.disabled)){choose.value=option.value;choose.dispatchEvent(new Event('change'));await lab.run();check(lab.element);}lab.setConfig(advancedOperationsDemoConfig('airport'),{replace:true});await lab.compareAdvanced();check(lab.element);const launch=createLaunchPanel();try{const input=launch.element.querySelector('input');input.value='-1';input.dispatchEvent(new Event('input'));check(launch.element);}finally{launch.destroy();}}finally{lab.destroy();restore();}});
import {bayExperimentSteps,freezeBayExperiment} from '../src/model/bay-experiment-contract.js';
import {advancedComparisonView} from '../src/ui/advanced-operations-view.js';
import {createRegionalPowerPanel} from '../src/ui/regional-power-view.js';
import {depotReadinessDemoConfig} from '../src/model/bay-operations.js';
test('real staffing, Street compare, both launch templates, Austin and all advanced treatments show generated readable lines',async()=>{const restore=installFakeDom();try{
 const lab=createOperationsLab();try{lab.loadScenario(depotReadinessDemoConfig());await lab.run();await lab.compareReadiness();check(lab.element);assert.ok(lab.element.querySelector('.ops-readiness-comparison .teaching-run-line'));}finally{lab.destroy();}
 const street=createStreetLab();try{await street.run(true);check(street.element);for(const b of street.element.querySelectorAll('button[aria-disabled]')){assert.equal(b.disabled,false);assert.equal(b.getAttribute('aria-disabled'),'false');}assert.match(street.element.textContent,/Mixed trade-off/);}finally{street.destroy();}
 for(const template of ['peninsula','region_b']){const p=createLaunchPanel();try{p.chooseTemplate(template);await p.run();check(p.element);for(const b of p.element.querySelectorAll('button[aria-disabled]'))assert.equal(b.getAttribute('aria-disabled'),'false');assert.ok(p.element.querySelector('.teaching-run-line'));}finally{p.destroy();}}
 const a=createRegionalPowerPanel();try{await a.run();check(a.element);for(const b of a.element.querySelectorAll('button[aria-disabled]'))assert.equal(b.getAttribute('aria-disabled'),'false');assert.ok(a.element.querySelector('.teaching-run-line'));}finally{a.destroy();}
 for(const [kind,treatment]of [['charging','charging_redistribution'],['charging','charging_deadlines'],['resources','resource_freshness'],['airport','airport_forecast']]){const steps=bayExperimentSteps(freezeBayExperiment(advancedOperationsDemoConfig(kind),{treatment,seeds:[1001,1002],resamples:1000}));let next;do{next=steps.next();}while(!next.done);const node=advancedComparisonView(next.value);check(node);assert.ok(node.querySelector('.teaching-run-line').textContent.length<=240,treatment);}
 check(advancedComparisonView({validity:'INVALID_EXPERIMENT',reason:'Use 1,000 to 10,000 resamples.',replications:0,analysis:null}));
 }finally{restore();}});
test('Austin names the exact recorded power condition for every built-in condition',async()=>{const restore=installFakeDom(),panel=createRegionalPowerPanel();try{for(const [id,label]of [['full','Full power condition'],['moderate','60% power condition'],['severe','20% power condition'],['outage','Power outage']]){const select=panel.element.querySelector('[aria-label="Regional power condition"]');select.value=id;select.dispatchEvent(new Event('change'));const r=await panel.run();assert.equal(r.config.site_power_profile.condition_id,'tx-aus-'+id+'-v1');assert.ok(panel.element.querySelector('.teaching-run-line').textContent.includes(label));}}finally{panel.destroy();restore();}});
test('capacity and full-cycle lessons use recorded trials and the first ready event',async()=>{const {simulationCatalog}=await import('../src/ui/simulation-catalog.js');const restore=installFakeDom(),lab=createOperationsLab();try{await lab.compareCapacity();assert.ok(lab.element.querySelector('.ops-capacity-content .teaching-run-line'));check(lab.element);const lesson=simulationCatalog().find(r=>r.id==='full-cycle');lab.loadScenario(lesson.patch);lab.setLesson(lesson);await lab.run();const r=lab.getState().result;assert.equal(lab.element.querySelector('[aria-label="Follow a car"]').value,r.events.find(e=>e.kind==='ready').vehicle_id);}finally{lab.destroy();restore();}});
test('actual four-area app, walkthrough and quoted panels mount under the same human-copy scan',async()=>{const {start}=await import('../src/ui/app.js'),restore=installFakeDom();const root=document.createElement('div'),strip=document.createElement('div');root.id='fleetlab-root';strip.id='fleetlab-teaching-strip';root.appendChild(strip);document.body.appendChild(root);const app=start({createWorker:()=>null,studio:true});try{for(const route of ['#/','#/approach','#/regional','#/experiments','#/walkthrough']){app.studio.applyRoute(route);check(app.studio.element);}}finally{app.destroy();restore();}});
