import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,symlinkSync,rmSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {buildSite,buildHtml} from '../tools/pack.mjs';
import {checkSite,checkDist,MAX_BYTES} from '../tools/check-dist.mjs';
import {MP4,WEBP} from './helpers/film-fixtures.mjs';
const MEDIA='src/ui/hero-media.js';
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'film-pack-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const files={'index.html':'<html><head></head><body></body></html>','styles.css':'body {color:black}', 'src/runtime/worker.js':'export const worker = 1;', 'src/ui/labels.js':'export const label = "hello";', 'src/ui/app.js':'import {FILM_URL, POSTER_URL} from "./hero-media.js"; import {label} from "./labels.js"; export function start(){ return [FILM_URL,POSTER_URL,label]; }',[MEDIA]:readFileSync(new URL('../src/ui/hero-media.js',import.meta.url),'utf8'),'media/fleet-film.mp4':MP4,'media/fleet-film-poster.webp':WEBP};
 for(const [name,data]of Object.entries(files)){mkdirSync(dirname(join(dir,name)),{recursive:true});writeFileSync(join(dir,name),data);}return dir;}
test('hosted media preserves real binary bytes; offline embeds only the poster',t=>{const dir=fixture(t),site=buildSite(dir);assert.deepEqual(site.get('media/fleet-film.mp4'),MP4);assert.deepEqual(site.get('media/fleet-film-poster.webp'),WEBP);assert.deepEqual(checkSite(site,{requiredLabels:['fixture forbidden label']}),[]);const offline=buildHtml(dir);assert.ok(offline.includes(WEBP.toString('base64')));assert.ok(!offline.includes('fleet-film.mp4'));assert.deepEqual(checkDist(offline,{requiredLabels:['fixture forbidden label']}),[]);assert.equal(MAX_BYTES,2.5*1024*1024);});
for(const kind of ['unexpected','format','symlink','oversize','directory-symlink'])test('packer rejects '+kind+' media',t=>{const dir=fixture(t);const path=join(dir,'media/fleet-film.mp4');if(kind==='unexpected')writeFileSync(join(dir,'media/extra.bin'),MP4);if(kind==='format')writeFileSync(path,WEBP);if(kind==='oversize')writeFileSync(path,Buffer.alloc(4*1024*1024+1));if(kind==='symlink'){rmSync(path);symlinkSync('/tmp/absent-film',path);}if(kind==='directory-symlink'){rmSync(join(dir,'media'),{recursive:true});symlinkSync('/tmp',join(dir,'media'));}assert.throws(()=>buildSite(dir),/media|film|format|size|symlink/i);assert.throws(()=>buildHtml(dir),/media|film|format|size|symlink/i);});
test('checker enforces independent media caps and still scans every code module',t=>{const site=buildSite(fixture(t));site.set('media/fleet-film-poster.webp',Buffer.alloc(200*1024+1));assert.match(checkSite(site,{requiredLabels:['fixture forbidden label']}).join('\n'),/size|limit/);site.set('media/fleet-film-poster.webp',WEBP);site.set('media/extra.bin',MP4);assert.match(checkSite(site,{requiredLabels:['fixture forbidden label']}).join('\n'),/unexpected|not text/);site.delete('media/extra.bin');site.set('src/ui/hidden.js','fetch("https://example.test");');assert.match(checkSite(site,{requiredLabels:['fixture forbidden label']}).join('\n'),/fetch|scheme|URL/);site.delete('src/ui/hidden.js');site.set('styles.css',' '.repeat(MAX_BYTES));assert.match(checkSite(site,{requiredLabels:['fixture forbidden label']}).join('\n'),/size/);});
test('source and offline budgets cannot be enlarged by the optional film',t=>{const dir=fixture(t);writeFileSync(join(dir,'styles.css'),' '.repeat(MAX_BYTES));assert.throws(()=>buildSite(dir),/source byte limit/);assert.throws(()=>buildHtml(dir),/offline byte limit/);});
test('checker rejects corrupt or missing hosted binaries',t=>{const site=buildSite(fixture(t));site.set('media/fleet-film.mp4',WEBP);assert.match(checkSite(site,{requiredLabels:['fixture forbidden label']}).join('\n'),/format/);site.set('media/fleet-film.mp4',Buffer.alloc(4*1024*1024+1));assert.match(checkSite(site,{requiredLabels:['fixture forbidden label']}).join('\n'),/size/);site.delete('media/fleet-film.mp4');assert.match(checkSite(site,{requiredLabels:['fixture forbidden label']}).join('\n'),/missing/);});
