import assert from 'node:assert/strict';
import {test} from 'node:test';
import {installFakeDom} from './helpers/fake-dom.mjs';
import {createHeroFilm} from '../src/ui/hero-film.js';

function setup({reduced=false,reducedMotion,pending=false,denied=false,nativeStart=false,noObserver=false,filmUrl,autoplay,saveData=false}={}) {
  const restore=installFakeDom(globalThis,{media:{'(prefers-reduced-motion: reduce)':reduced}});
  let observer, complete, rejectPlay, plays=0, pauses=0;
  const connection=document.createElement('span');connection.saveData=saveData;window.navigator={connection};
  window.IntersectionObserver=class {constructor(cb){this.cb=cb;observer=this;} observe(){} disconnect(){this.disconnected=true;}};
  if(noObserver)delete window.IntersectionObserver;
  const create=document.createElement.bind(document);
  document.createElement=(tag)=>{const node=create(tag); if(tag==='video'){
    node.paused=true;node.currentTime=0;
    node.pause=()=>{pauses++;node.paused=true;node.dispatchEvent(new Event('pause'));};
    node.play=()=>{plays++;if(denied)return Promise.reject(new Error('denied')); if(nativeStart){node.paused=false;node.dispatchEvent(new Event('play'));} return new Promise((resolve,reject)=>{rejectPlay=(name)=>{node.paused=true;reject(Object.assign(new Error(name),{name}));};complete=()=>{node.paused=false;node.dispatchEvent(new Event('playing'));resolve();};if(!pending)complete();});};
    node.load=()=>{};
  }return node;};
  const hero=createHeroFilm({reducedMotion,autoplay,...(filmUrl===undefined?{}:{filmUrl,posterUrl:'data:image/webp;base64,AAAA'})});
  document.body.appendChild(hero.element);hero.setActive(true);
  const video=hero.element.querySelector('video'),button=hero.element.querySelector('button');
  return {hero,video,button,restore,connection,show:(visible=true)=>observer.cb([{isIntersecting:visible,intersectionRatio:visible?1:0}]),complete:()=>complete(),reject:(name='AbortError')=>rejectPlay(name),get plays(){return plays;},get pauses(){return pauses;},intersect:(entry)=>observer.cb([entry]),get observer(){return observer;}};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
for(const [name,preference] of [['system reduced motion',{reduced:true}],['a reduced-motion override',{reducedMotion:()=>true}],['data saving',{saveData:true}],['the rollback flag',{autoplay:false}]])test(`the film waits for a click under ${name}`,async()=>{const x=setup(preference);try{x.show();await tick();assert.equal(x.plays,0);assert.equal(x.video.getAttribute('src'),null);assert.equal(x.button.textContent,'Play film');x.button.click();await tick();assert.equal(x.plays,1);assert.equal(x.button.textContent,'Pause film');}finally{x.hero.destroy();x.restore();}});
test('changing the effective motion preference clears a prior film opt-in and pauses immediately',async()=>{let reduced=false;const x=setup({reducedMotion:()=>reduced});try{x.show();await tick();assert.equal(x.video.paused,false);reduced=true;x.hero.setActive(true);assert.equal(x.video.paused,true);const plays=x.plays;x.show(false);x.show();await tick();assert.equal(x.plays,plays);x.button.click();await tick();assert.equal(x.plays,plays+1);}finally{x.hero.destroy();x.restore();}});
test('returning to Home after leaving does not restart the film without a click',async()=>{const x=setup();try{x.show();await tick();assert.equal(x.video.muted,true);assert.equal(x.button.textContent,'Pause film');x.hero.setActive(false);assert.equal(x.video.paused,true);x.hero.setActive(true);x.show();await tick();assert.equal(x.plays,1);assert.equal(x.video.paused,true);assert.equal(x.button.textContent,'Play film');}finally{x.hero.destroy();x.restore();}});
test('a paused film stays paused across visibility changes',async()=>{const x=setup();try{x.show();await tick();x.button.click();document.dispatchEvent(new Event('visibilitychange'));x.show(false);x.show();await tick();assert.equal(x.plays,1);assert.equal(x.video.paused,true);}finally{x.hero.destroy();x.restore();}});
test('scrolling the playing film out of view automatically resumes the same playhead',async()=>{const x=setup();try{x.show();await tick();x.video.currentTime=6.25;x.show(false);assert.equal(x.video.paused,true);x.show();await tick();assert.equal(x.plays,2);assert.equal(x.video.currentTime,6.25);assert.equal(x.button.textContent,'Pause film');}finally{x.hero.destroy();x.restore();}});
for(const hide of ['navigation','document','intersection','destroy'])test('pending play is cancelled by '+hide,async()=>{const x=setup({pending:true});try{x.show();assert.equal(x.plays,1);if(hide==='navigation')x.hero.setActive(false);if(hide==='document'){document.hidden=true;document.dispatchEvent(new Event('visibilitychange'));}if(hide==='intersection')x.show(false);if(hide==='destroy')x.hero.destroy();x.complete();await tick();assert.equal(x.video.paused,true);assert.match(x.button.textContent,/Play/);if(hide==='destroy'){assert.equal(x.observer.disconnected,true);const n=x.plays;x.button.click();assert.equal(x.plays,n);}}finally{x.hero.destroy();x.restore();}});
test('a denied automatic play shows the unavailable status without retrying',async()=>{const x=setup({denied:true});try{x.show();await tick();assert.equal(x.hero.element.querySelector('.film-status').textContent,'Film unavailable. The concept image is shown.');x.show(false);x.show();document.dispatchEvent(new Event('visibilitychange'));x.hero.setActive(false);x.hero.setActive(true);await tick();assert.equal(x.plays,1);assert.equal(x.button.textContent,'Play film');assert.equal(x.hero.element.querySelector('img').hidden,false);}finally{x.hero.destroy();x.restore();}});
test('decode failure restores poster and truthful playback control',async()=>{const x=setup();try{x.show();await tick();x.video.dispatchEvent(new Event('error'));assert.equal(x.video.paused,true);assert.equal(x.hero.element.querySelector('img').hidden,false);assert.match(x.button.textContent,/Play/);}finally{x.hero.destroy();x.restore();}});
test('offline poster has no film or playback button',()=>{const x=setup({filmUrl:''});try{assert.equal(x.video,null);assert.equal(x.button,null);assert.ok(x.hero.element.querySelector('img').getAttribute('alt'));}finally{x.hero.destroy();x.restore();}});

test('observer absence stays on poster across visibility changes until explicit play',async()=>{const x=setup({noObserver:true});try{document.dispatchEvent(new Event('visibilitychange'));await tick();assert.equal(x.plays,0);assert.equal(x.video.getAttribute('src'),null);x.button.click();await tick();assert.equal(x.plays,1);}finally{x.hero.destroy();x.restore();}});
test('native pause events update the visible control',async()=>{const x=setup();try{x.show();await tick();x.video.pause();assert.match(x.button.textContent,/Play/);}finally{x.hero.destroy();x.restore();}});
test('destruction removes document and preference listeners',async()=>{const x=setup();try{x.show();await tick();x.hero.destroy();const count=x.pauses;document.hidden=true;document.dispatchEvent(new Event('visibilitychange'));x.restore.dom.media.set('(prefers-reduced-motion: reduce)',true);assert.equal(x.pauses,count);}finally{x.hero.destroy();x.restore();}});
test('a click after returning while an old play request settles starts one fresh request',async()=>{const x=setup({pending:true});try{x.show();x.hero.setActive(false);x.hero.setActive(true);x.button.click();assert.equal(x.plays,1);assert.match(x.button.textContent,/Cancel loading/);x.complete();await tick();assert.equal(x.plays,2);x.complete();await tick();assert.equal(x.video.paused,false);assert.match(x.button.textContent,/Pause/);}finally{x.hero.destroy();x.restore();}});

test('an aborted old request after a click on return starts one fresh request',async()=>{const x=setup({pending:true});try{x.show();x.hero.setActive(false);x.hero.setActive(true);x.button.click();x.reject();await tick();assert.equal(x.plays,2);x.complete();await tick();assert.equal(x.video.paused,false);assert.match(x.button.textContent,/Pause/);}finally{x.hero.destroy();x.restore();}});
test('a stale denial after a click on return stays blocked across visibility changes',async()=>{const x=setup({pending:true});try{x.show();x.hero.setActive(false);x.hero.setActive(true);x.button.click();x.reject('NotAllowedError');await tick();x.show(false);x.show();await tick();assert.equal(x.plays,1);assert.match(x.button.textContent,/Play/);}finally{x.hero.destroy();x.restore();}});
test('native play sets paused false before playing and the second click visibly pauses',async()=>{const x=setup({pending:true,nativeStart:true,reduced:true});try{x.show();x.button.click();assert.equal(x.video.paused,false);assert.match(x.button.textContent,/Pause/);assert.match(x.button.getAttribute('aria-label'),/Pause/);x.button.click();assert.equal(x.video.paused,true);assert.match(x.button.textContent,/Play/);x.reject();await tick();x.hero.setActive(false);x.hero.setActive(true);assert.equal(x.plays,1);}finally{x.hero.destroy();x.restore();}});
test('pending loading exposes cancel and returns to Play after cancellation',async()=>{const x=setup({pending:true,reduced:true});try{x.show();x.button.click();assert.match(x.button.textContent,/Cancel loading/);assert.match(x.button.getAttribute('aria-label'),/Cancel/);x.button.click();assert.match(x.button.textContent,/Play/);x.reject();await tick();assert.equal(x.plays,1);}finally{x.hero.destroy();x.restore();}});

test('eligible visible film starts silently inline without a click and never loops',async()=>{const x=setup();try{assert.equal(x.video.getAttribute('src'),null);assert.equal(x.plays,0);x.show();await tick();assert.equal(x.plays,1);assert.equal(x.video.getAttribute('src'),'./media/fleet-film.mp4');assert.equal(x.video.muted,true);assert.equal(x.video.hasAttribute('playsinline'),true);assert.equal(x.video.hasAttribute('loop'),false);assert.equal(x.video.getAttribute('preload'),'none');assert.match(x.button.textContent,/Pause/);}finally{x.hero.destroy();x.restore();}});
test('a frame needs half its area visible before automatic source attachment',async()=>{const x=setup();try{x.intersect({isIntersecting:true,intersectionRatio:.49});await tick();assert.equal(x.plays,0);assert.equal(x.video.getAttribute('src'),null);x.intersect({isIntersecting:true,intersectionRatio:.5});await tick();assert.equal(x.plays,1);}finally{x.hero.destroy();x.restore();}});
test('an oversized frame needs half the viewport height and horizontal visibility',async()=>{const x=setup();try{const frame={width:500,height:1200},root={height:800};const show=(height,width=500)=>x.intersect({isIntersecting:width>0,intersectionRatio:height/1200,boundingClientRect:frame,rootBounds:root,intersectionRect:{height,width}});show(399);assert.equal(x.plays,0);show(400,0);assert.equal(x.plays,0);show(400);await tick();assert.equal(x.plays,1);}finally{x.hero.destroy();x.restore();}});
test('hidden document never attaches an automatic source',async()=>{const x=setup();try{document.hidden=true;x.show();await tick();assert.equal(x.plays,0);assert.equal(x.video.getAttribute('src'),null);document.hidden=false;document.dispatchEvent(new Event('visibilitychange'));await tick();assert.equal(x.plays,1);}finally{x.hero.destroy();x.restore();}});
test('hidden-page pause resumes from the same clock',async()=>{const x=setup();try{x.show();await tick();x.video.currentTime=7.75;document.hidden=true;document.dispatchEvent(new Event('visibilitychange'));assert.equal(x.video.paused,true);document.hidden=false;document.dispatchEvent(new Event('visibilitychange'));await tick();assert.equal(x.plays,2);assert.equal(x.video.currentTime,7.75);}finally{x.hero.destroy();x.restore();}});
test('ended film keeps its final frame and Replay across visibility and BFCache restoration',async()=>{const x=setup();try{x.show();await tick();x.video.currentTime=12;x.video.paused=true;x.video.dispatchEvent(new Event('ended'));assert.match(x.button.textContent,/Replay/);assert.equal(x.hero.element.querySelector('img').hidden,true);x.show(false);x.show();window.dispatchEvent(new Event('pagehide'));window.dispatchEvent(new Event('pageshow'));await tick();assert.equal(x.plays,1);assert.equal(x.video.currentTime,12);assert.match(x.button.textContent,/Replay/);x.button.click();await tick();assert.equal(x.plays,2);assert.equal(x.video.currentTime,0);assert.match(x.button.textContent,/Pause/);}finally{x.hero.destroy();x.restore();}});
test('Pause survives BFCache, resize, rerender and visibility changes',async()=>{const x=setup();try{x.show();await tick();x.button.click();window.dispatchEvent(new Event('pagehide'));window.dispatchEvent(new Event('pageshow'));window.dispatchEvent(new Event('resize'));x.hero.setActive(true);x.show(false);x.show();document.hidden=true;document.dispatchEvent(new Event('visibilitychange'));document.hidden=false;document.dispatchEvent(new Event('visibilitychange'));await tick();assert.equal(x.plays,1);assert.equal(x.video.paused,true);assert.match(x.button.textContent,/Play/);}finally{x.hero.destroy();x.restore();}});
test('manual Pause during initial loading survives late fulfillment',async()=>{const x=setup({pending:true});try{x.show();assert.match(x.button.textContent,/Cancel/);x.button.click();x.complete();await tick();x.show(false);x.show();assert.equal(x.plays,1);assert.equal(x.video.paused,true);assert.match(x.button.textContent,/Play/);assert.equal(x.hero.element.querySelector('img').hidden,false);}finally{x.hero.destroy();x.restore();}});
for(const type of ['system motion','data saving'])test(`${type} enabled during playback cancels visibility resume until explicit Play`,async()=>{const x=setup();try{x.show();await tick();if(type==='system motion')x.restore.dom.media.set('(prefers-reduced-motion: reduce)',true);else{x.connection.saveData=true;x.connection.dispatchEvent(new Event('change'));}assert.equal(x.video.paused,true);if(type==='system motion')x.restore.dom.media.set('(prefers-reduced-motion: reduce)',false);else{x.connection.saveData=false;x.connection.dispatchEvent(new Event('change'));}x.show(false);x.show();await tick();assert.equal(x.plays,1);x.button.click();await tick();assert.equal(x.plays,2);}finally{x.hero.destroy();x.restore();}});
test('preference change during loading defeats a late playing event and fulfillment',async()=>{const x=setup({pending:true});try{x.show();assert.equal(x.plays,1);x.restore.dom.media.set('(prefers-reduced-motion: reduce)',true);x.complete();await tick();x.restore.dom.media.set('(prefers-reduced-motion: reduce)',false);x.show(false);x.show();assert.equal(x.plays,1);assert.equal(x.video.paused,true);assert.equal(x.hero.element.querySelector('img').hidden,false);}finally{x.hero.destroy();x.restore();}});
test('a pending automatic start may resume after visibility returns with no stale playing state',async()=>{const x=setup({pending:true});try{x.show();assert.equal(x.plays,1);x.show(false);x.show();x.complete();await tick();assert.equal(x.plays,2);assert.equal(x.video.paused,true);assert.match(x.button.textContent,/Cancel/);x.complete();await tick();assert.equal(x.video.paused,false);assert.match(x.button.textContent,/Pause/);}finally{x.hero.destroy();x.restore();}});
test('remounting in the same document cannot create another automatic visit',async()=>{const x=setup();let second;try{x.show();await tick();x.hero.destroy();second=createHeroFilm();document.body.appendChild(second.element);second.setActive(true);x.show();await tick();assert.equal(x.plays,1);assert.equal(second.element.querySelector('video').getAttribute('src'),null);second.element.querySelector('button').click();await tick();assert.equal(x.plays,2);}finally{second?.destroy();x.hero.destroy();x.restore();}});

test('manual reduced-motion playback does not automatically resume after leaving view',async()=>{const x=setup({reduced:true});try{x.show();x.button.click();await tick();assert.equal(x.plays,1);x.video.currentTime=3;x.show(false);x.show();await tick();assert.equal(x.plays,1);assert.equal(x.video.currentTime,3);assert.equal(x.video.paused,true);x.button.click();await tick();assert.equal(x.plays,2);}finally{x.hero.destroy();x.restore();}});
test('an ended film keeps Replay when motion preference changes',async()=>{const x=setup();try{x.show();await tick();x.video.paused=true;x.video.dispatchEvent(new Event('ended'));x.restore.dom.media.set('(prefers-reduced-motion: reduce)',true);assert.match(x.button.textContent,/Replay/);x.restore.dom.media.set('(prefers-reduced-motion: reduce)',false);x.show(false);x.show();await tick();assert.equal(x.plays,1);assert.match(x.button.textContent,/Replay/);}finally{x.hero.destroy();x.restore();}});
test('BFCache temporarily pauses playing media and resumes its existing clock',async()=>{const x=setup();try{x.show();await tick();x.video.currentTime=4.5;window.dispatchEvent(new Event('pagehide'));assert.equal(x.video.paused,true);window.dispatchEvent(new Event('pageshow'));await tick();assert.equal(x.plays,2);assert.equal(x.video.currentTime,4.5);assert.match(x.button.textContent,/Pause/);}finally{x.hero.destroy();x.restore();}});
test('reduced-data media preference vetoes source attachment and accepts explicit playback',async()=>{const x=setup();try{x.restore.dom.media.set('(prefers-reduced-data: reduce)',true);x.show();await tick();assert.equal(x.plays,0);assert.equal(x.video.getAttribute('src'),null);x.button.click();await tick();assert.equal(x.plays,1);}finally{x.hero.destroy();x.restore();}});
test('late playing events after manual Pause cannot reveal or restart stale media',async()=>{const x=setup({pending:true});try{x.show();x.button.click();x.video.paused=false;x.video.dispatchEvent(new Event('playing'));assert.equal(x.video.paused,true);assert.equal(x.hero.element.querySelector('img').hidden,false);x.complete();await tick();assert.equal(x.video.paused,true);assert.match(x.button.textContent,/Play/);}finally{x.hero.destroy();x.restore();}});
test('a queued playing event cannot hide the poster while the media is actually paused',async()=>{const x=setup({pending:true});try{x.show();assert.equal(x.plays,1);assert.equal(x.video.paused,true);x.video.dispatchEvent(new Event('playing'));assert.equal(x.hero.element.querySelector('img').hidden,false);assert.match(x.button.textContent,/Cancel/);x.complete();await tick();assert.equal(x.hero.element.querySelector('img').hidden,true);}finally{x.hero.destroy();x.restore();}});
test('scroll geometry detects an oversized visibility threshold between observer callbacks',async()=>{const x=setup();try{let top=401;x.hero.element.getBoundingClientRect=()=>({left:10,right:510,top,bottom:top+1200,width:500,height:1200});window.dispatchEvent(new Event('scroll'));assert.equal(x.plays,0);assert.equal(x.video.getAttribute('src'),null);top=400;window.dispatchEvent(new Event('scroll'));await tick();assert.equal(x.plays,1);x.video.currentTime=2;top=500;window.dispatchEvent(new Event('resize'));assert.equal(x.video.paused,true);top=400;window.dispatchEvent(new Event('resize'));await tick();assert.equal(x.plays,2);assert.equal(x.video.currentTime,2);}finally{x.hero.destroy();x.restore();}});
test('an explicit site full-motion override permits the initial automatic instance',async()=>{const x=setup({reduced:true,reducedMotion:()=>false});try{x.show();await tick();assert.equal(x.plays,1);assert.match(x.button.textContent,/Pause/);x.button.click();x.show(false);x.show();await tick();assert.equal(x.plays,1);assert.equal(x.video.paused,true);}finally{x.hero.destroy();x.restore();}});
